# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: webhook

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/webhook.yml
      - webhook/**
      - '*.tf'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/webhook.yml
      - webhook/**
      - '*.tf'
  workflow_dispatch: # Manual runs
  schedule: # Run tests every day at UTC 18:00 (11am in Pacific Time for solar energy)
    - cron: '0 18 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Cache linter
        uses: actions/cache@v4
        with:
          path: webhook/env
          key: ${{ runner.os }}-lint

      - name: Install linter
        working-directory: webhook
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install ruff
          pip check

      - name: Run linter
        working-directory: webhook
        run: |
          source env/bin/activate
          ruff check .

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # To parse datetime in ISO format ending with Z, we need at least Python 3.11.
        # https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat
        python-version: ['3.12']

    env:
      PROJECT_ID: jss-16p1-test
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    # Needed to generate the identity token for google-github-actions/auth.
    # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read   # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # https://github.com/marketplace/actions/authenticate-to-google-cloud
      # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/897785740795/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@jss-16p1-test.iam.gserviceaccount.com

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: webhook/env
          key: ${{ runner.os }}-test-${{ hashFiles('webhook/requirements.txt', 'webhook/requirements-test.txt') }}

      - name: Install dependencies
        working-directory: webhook
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt
          pip check

      - name: Type check
        working-directory: webhook
        run: |
          source env/bin/activate
          mypy --non-interactive --install-types .

      - name: Run tests
        working-directory: webhook
        run: |
          source env/bin/activate
          pytest --verbose -s -W ignore::DeprecationWarning
